import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/MainComponents/Navbar";
import Footer from "@/components/MainComponents/Footer";
import LoadingScreen from "@/components/MainComponents/LoadingScreen";
import { LanguageProvider } from "@/context/LanguageContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Volunteer",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/logo-volunteer.png", sizes: "180x180" },
    { rel: "apple-touch-icon", url: "/logo-volunteer.png", sizes: "180x180" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LanguageProvider>
        <body
          className={`${montserrat.className} min-h-screen bg-white text-textColor flex flex-col`}
        >
          {/* <LoadingScreen /> */}
          <Navbar />
          <main className="">{children}</main>
          <Footer />
        </body>
      </LanguageProvider>
    </html>
  );
}
